name: LoopMi Edge
version: "0.1.19"
slug: loopmi_edge
description: Production-grade LoopMi Edge runtime for Home Assistant Add-on.
url: https://github.com/yaggii/LoopMi-Addons
image: ghcr.io/yaggii/loopmi-edge
startup: application
boot: auto
init: false
homeassistant_api: true
arch:
  - aarch64
watchdog: http://[HOST]:5034/health
ports:
  5034/tcp: 5034
ports_description:
  5034/tcp: LoopMi Edge REST API
map:
  - addon_config:rw
options: {}
schema: {}
